### ISSUE TITLE
Error in quickstart example on home page

### ISSUE THREAD

**Issue by netcarver** [clue/framework-x#119]
Hi @clue, @SimonFrings 

Couldn't find the source for the home page of the website - but there is a syntax error in the hero quickstart example.

![2022-02-20_15-23](https://user-images.githubusercontent.com/16049/154850103-0190708e-69cb-49b0-adf4-3a4a84ee96ee.png)

**Comment by SimonFrings** [comment]
@netcarver Thanks for pointing that out, nice catch :+1: 

We're aware that it's not 100% clear where to contribute to the website/documentation, the same thing happened to me some weeks ago. ^^
For that reason we're currently writing some documentation for contributors to know where to start! In your case you need to access [clue/framework-x-website](https://github.com/clue/framework-x-website) and find the `index.html`. In there are all the examples that can be seen on the main page of the website.

It's up to you now, do you want to fill in a PR that fixes this or do you want me to do it?

**Comment by SimonFrings** [comment]
@netcarver This has already been fixed in clue/framework-x-website#25 by @nazmulpcc!

Thanks again to the both of you :rocket:
