### ISSUE TITLE
Documentation about 'nginx reverse proxy' is at least misleading

### ISSUE THREAD

**Issue by virtuelle-maschine** [clue/framework-x#195]
I have tried to build a setup with two services: one framework-x service and a nginx as reverse proxy.
If I am using the nginx configuration that you are suggesting (https://framework-x.org/docs/best-practices/deployment/#nginx-reverse-proxy), all php files in the public folder are served "as-it" (unparsed) to the client (at least if nginx and framework-x are sharing the same public folder - but that is how I read your examples).
Seems to me that using a different path for the the framework-x start script than /public/index.php is highly recommended. Or am I missing something?

I have created an example in a branch of my test project: https://github.com/virtuelle-maschine/framework-x-test/tree/example-with-index
An example that works as expected can be found in the main branch of that project.

BTW, regarding Dockerfile: I am surprised you are using the ENTRYPOINT instruction to start the app - doesn't the CMD instruction makes more sense as you can run the container with a different command (e.g. composer) much easier?

**Comment by SimonFrings** [comment]
@virtuelle-maschine Thanks for bringing this up :+1:

> Seems to me that using a different path for the the framework-x start script than /public/index.php is highly recommended. Or am I missing something?

I agree, the documentation can definitely be improved there, if you have any suggestions we are always happy about PRs, I wrote a [contribution chapter](https://github.com/clue/framework-x#contribute) for our readme a while ago, in there are instructions on how to work on the documentation.

> BTW, regarding Dockerfile: I am surprised you are using the ENTRYPOINT instruction to start the app - doesn't the CMD instruction makes more sense as you can run the container with a different command (e.g. composer) much easier?

This makes actually no difference in our case. If you think it is necessary to tackle this topic, we're happy to hear your thoughts on this, or you can suggest changes via a pull request.

**Comment by virtuelle-maschine** [comment]
@SimonFrings Thanks for your reply! Created PR #197 to fix the nginx reverse proxy configuration.
